

services:
  db:
    image: mysql:5.7
    container_name: mysql2
    networks:
      - beispiel-netzwerk
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}


    volumes:
      - db_mysql_save:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend: 
    build: ./
    image: node-backend
    container_name: mein-backend
    networks:
      - beispiel-netzwerk
    ports:
      - "4000:${NODE_PORT}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      PORT: ${NODE_PORT}

  

volumes:
  db_mysql_save:

networks:
  beispiel-netzwerk:
    driver: bridge